export * from './FirstForm/FirstForm'
export * from './GameCard/GameCard'
export * from './GameModal/GameModal'
export * from './GameTable/GameTable'
export * from './NewGameModal/NewGameModal'
export * from './QuestionModal/QuestionModal'
export * from './QuestionsForm/QuestionsForm'
export * from './SecondForm/SecondForm'
